const GET_RECIPES = "GET_RECIPES"
const ERROR = "ERROR"
const FILTER_DIET = "FILTER_DIET"
const FILTER_WHERE ="FILTER_WHERE"
const FILTER_AS_DES = "FILTER_AS_DES"


module.exports ={
    GET_RECIPES,
    ERROR,
    FILTER_DIET,
    FILTER_WHERE,
    FILTER_AS_DES,
}